//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::courses::Entity as Courses;
pub use super::forum_channels::Entity as ForumChannels;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
